keyword_list = [{'count': '3586', 'label': 'Mathematics', 'name': '수'},
 {'count': '1384,330', 'label': 'Mathematics,Number_theory', 'name': '정수'},
 {'count': '692', 'label': 'Mathematics', 'name': '자연수'},
 {'count': '493,343,369,94',
  'label': 'Mathematics,Dynamic_programming,Data_structures,String',
  'name': '수열'},
 {'count': '434', 'label': 'Mathematics', 'name': '합'},
 {'count': '402,361,369,189,473,46',
  'label': 'Mathematics,Graph_theory,Data_structures,Greedy,String,Stack',
  'name': '길이'},
 {'count': '398,110', 'label': 'Mathematics,Number_theory', 'name': '나머지'},
 {'count': '396,539', 'label': 'Mathematics,Graph_theory', 'name': '사이'},
 {'count': '377,457,556,326,186,56',
  'label': 'Mathematics,Dynamic_programming,Implementation,Graph_theory,String,Stack',
  'name': '순서'},
 {'count': '355,457,261,308,262,144,71,42',
  'label': 'Mathematics,Dynamic_programming,Implementation,Graph_theory,Greedy,Graph_traversal,Breadth_first_search,Priority_queue',
  'name': '최대'},
 {'count': '314,33,261',
  'label': 'Mathematics,Implementation,Number_theory',
  'name': '소수'},
 {'count': '309,89,29',
  'label': 'Mathematics,Graph_theory,Binary_search',
  'name': '자리'},
 {'count': '298,282', 'label': 'Mathematics,Implementation', 'name': '계산'},
 {'count': '296,544,528,364',
  'label': 'Mathematics,Implementation,Graph_theory,Data_structures',
  'name': '위치'},
 {'count': '208,200,206,202,119',
  'label': 'Mathematics,Implementation,Graph_theory,Data_structures,Graph_traversal',
  'name': '좌표'},
 {'count': '202,65', 'label': 'Mathematics,String', 'name': '표현'},
 {'count': '172', 'label': 'Mathematics', 'name': '확률'},
 {'count': '132,67,77,56',
  'label': 'Mathematics,Dynamic_programming,Graph_theory,Data_structures',
  'name': '행렬'},
 {'count': '123', 'label': 'Mathematics', 'name': '연산'},
 {'count': '117', 'label': 'Mathematics', 'name': '변'},
 {'count': '108,94', 'label': 'Mathematics,Data_structures', 'name': '집합'},
 {'count': '107', 'label': 'Mathematics', 'name': '양의'},
 {'count': '106', 'label': 'Mathematics', 'name': '배수'},
 {'count': '100', 'label': 'Mathematics', 'name': '진법'},
 {'count': '96,37', 'label': 'Mathematics,Number_theory', 'name': '분수'},
 {'count': '91,47', 'label': 'Mathematics,Number_theory', 'name': '약수'},
 {'count': '90', 'label': 'Mathematics', 'name': '함수'},
 {'count': '89', 'label': 'Mathematics', 'name': '기댓값'},
 {'count': '84', 'label': 'Mathematics', 'name': '공약수'},
 {'count': '83', 'label': 'Mathematics', 'name': '곱'},
 {'count': '80,164,65,139,102,55,17,23',
  'label': 'Mathematics,Dynamic_programming,Implementation,Graph_theory,Greedy,Breadth_first_search,Depth_first_search,Priority_queue',
  'name': '최솟값'},
 {'count': '75', 'label': 'Mathematics', 'name': '소수점'},
 {'count': '73', 'label': 'Mathematics', 'name': '제곱'},
 {'count': '72', 'label': 'Mathematics', 'name': '곱셈'},
 {'count': '68', 'label': 'Mathematics', 'name': '진수'},
 {'count': '66', 'label': 'Mathematics', 'name': '짝수'},
 {'count': '66,31,14',
  'label': 'Mathematics,Dynamic_programming,Data_structures',
  'name': '이진수'},
 {'count': '65,38,22,65',
  'label': 'Mathematics,Dynamic_programming,Implementation,Data_structures',
  'name': '순열'},
 {'count': '64', 'label': 'Mathematics', 'name': '실수'},
 {'count': '63', 'label': 'Mathematics', 'name': '수학'},
 {'count': '63', 'label': 'Mathematics', 'name': '홀수'},
 {'count': '60', 'label': 'Mathematics', 'name': '평균'},
 {'count': '52,18', 'label': 'Mathematics,Number_theory', 'name': '다항식'},
 {'count': '51', 'label': 'Mathematics', 'name': '계수'},
 {'count': '50', 'label': 'Mathematics', 'name': '분해'},
 {'count': '47', 'label': 'Mathematics', 'name': '근'},
 {'count': '47,81,29',
  'label': 'Mathematics,Implementation,Binary_search',
  'name': '정렬'},
 {'count': '47', 'label': 'Mathematics', 'name': '차원'},
 {'count': '46', 'label': 'Mathematics', 'name': '절댓값'},
 {'count': '45,28', 'label': 'Mathematics,Number_theory', 'name': '제곱수'},
 {'count': '42', 'label': 'Mathematics', 'name': '덧셈'},
 {'count': '42', 'label': 'Mathematics', 'name': '조합'},
 {'count': '37,11', 'label': 'Mathematics,Number_theory', 'name': '방정식'},
 {'count': '35', 'label': 'Mathematics', 'name': '반올림'},
 {'count': '33,29', 'label': 'Mathematics,Number_theory', 'name': '소인수'},
 {'count': '32', 'label': 'Mathematics', 'name': '순서쌍'},
 {'count': '30', 'label': 'Mathematics', 'name': '증명'},
 {'count': '29', 'label': 'Mathematics', 'name': '비율'},
 {'count': '29', 'label': 'Mathematics', 'name': '음수'},
 {'count': '29', 'label': 'Mathematics', 'name': '지수'},
 {'count': '29,40,22,15,6',
  'label': 'Mathematics,Dynamic_programming,Data_structures,Binary_search,Divide_and_conquer',
  'name': '이진'},
 {'count': '28', 'label': 'Mathematics', 'name': '자릿수'},
 {'count': '27,37,51',
  'label': 'Mathematics,Data_structures,String',
  'name': '수식'},
 {'count': '25,25', 'label': 'Mathematics,Number_theory', 'name': '공배수'},
 {'count': '21', 'label': 'Mathematics', 'name': '나눗셈'},
 {'count': '20', 'label': 'Mathematics', 'name': '양수'},
 {'count': '19', 'label': 'Mathematics', 'name': '모듈러'},
 {'count': '17', 'label': 'Mathematics', 'name': '오일러'},
 {'count': '17', 'label': 'Mathematics', 'name': '평균값'},
 {'count': '17', 'label': 'Mathematics', 'name': '차수'},
 {'count': '17', 'label': 'Mathematics', 'name': '유리수'},
 {'count': '16', 'label': 'Mathematics', 'name': '몫'},
 {'count': '16', 'label': 'Mathematics', 'name': '로그'},
 {'count': '15', 'label': 'Mathematics', 'name': '이항'},
 {'count': '15,13', 'label': 'Mathematics,Number_theory', 'name': '정수론'},
 {'count': '15', 'label': 'Mathematics', 'name': '공식'},
 {'count': '13', 'label': 'Mathematics', 'name': '부호'},
 {'count': '12', 'label': 'Mathematics', 'name': '벡터'},
 {'count': '10', 'label': 'Mathematics', 'name': '삼각수'},
 {'count': '5', 'label': 'Mathematics', 'name': '정수형'},
 {'count': '4', 'label': 'Mathematics', 'name': '4,294,967,295'},
 {'count': '1030,1010,894',
  'label': 'Dynamic_programming,Implementation,Graph_theory',
  'name': '번째'},
 {'count': '416,154,444,190,236,44',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Data_structures,Greedy,Priority_queue',
  'name': '최소'},
 {'count': '204,441,395,170,114,63',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Data_structures,Breadth_first_search,Depth_first_search',
  'name': '방향'},
 {'count': '165,53,55,93',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Greedy',
  'name': '최댓값'},
 {'count': '144,105,73',
  'label': 'Dynamic_programming,Implementation,String',
  'name': '연속'},
 {'count': '143,169,187,55,148,118',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Data_structures,Graph_traversal,Breadth_first_search',
  'name': '격자'},
 {'count': '138,202,33',
  'label': 'Dynamic_programming,Implementation,Greedy',
  'name': '규칙'},
 {'count': '135,110,203,150,53,108,48,25',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Graph_traversal,Bruteforcing,Breadth_first_search,Depth_first_search,Dijkstras',
  'name': '인접'},
 {'count': '125,294,137,22',
  'label': 'Dynamic_programming,Implementation,Data_structures,Priority_queue',
  'name': '배열'},
 {'count': '118', 'label': 'Dynamic_programming', 'name': '구간'},
 {'count': '109,105',
  'label': 'Dynamic_programming,Data_structures',
  'name': '종류'},
 {'count': '99', 'label': 'Dynamic_programming', 'name': '증가'},
 {'count': '88', 'label': 'Dynamic_programming', 'name': '가격'},
 {'count': '85', 'label': 'Dynamic_programming', 'name': '작업'},
 {'count': '76,17,40,6',
  'label': 'Dynamic_programming,Tree,Binary_search,Divide_and_conquer',
  'name': '1,000,000'},
 {'count': '76,52,150,48',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Tree',
  'name': '관계'},
 {'count': '76', 'label': 'Dynamic_programming', 'name': '서열'},
 {'count': '71,105',
  'label': 'Dynamic_programming,Implementation',
  'name': '과정'},
 {'count': '71', 'label': 'Dynamic_programming', 'name': '1,000,000,007'},
 {'count': '70,26,81,46',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Greedy',
  'name': '최대한'},
 {'count': '70,49,106,59,68',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Data_structures,Breadth_first_search',
  'name': '구역'},
 {'count': '66', 'label': 'Dynamic_programming', 'name': '점프'},
 {'count': '57,22',
  'label': 'Dynamic_programming,Data_structures',
  'name': '나열'},
 {'count': '57', 'label': 'Dynamic_programming', 'name': '박스'},
 {'count': '56', 'label': 'Dynamic_programming', 'name': '무게'},
 {'count': '49', 'label': 'Dynamic_programming', 'name': '계단'},
 {'count': '49,108,104,30',
  'label': 'Dynamic_programming,Graph_theory,Tree,Dijkstras',
  'name': '가중치'},
 {'count': '48,28',
  'label': 'Dynamic_programming,Implementation',
  'name': '패턴'},
 {'count': '46,63', 'label': 'Dynamic_programming,Graph_theory', 'name': '체스'},
 {'count': '41,34,8,53,12,6',
  'label': 'Dynamic_programming,Greedy,Tree,Binary_search,Divide_and_conquer,Priority_queue',
  'name': '1,000,000,000'},
 {'count': '40,48,26',
  'label': 'Dynamic_programming,Graph_theory,Greedy',
  'name': '최소한'},
 {'count': '40,34,15',
  'label': 'Dynamic_programming,Graph_theory,Greedy',
  'name': '최적'},
 {'count': '40', 'label': 'Dynamic_programming', 'name': '고구마'},
 {'count': '39,45,31',
  'label': 'Dynamic_programming,Implementation,Graph_theory',
  'name': '아래쪽'},
 {'count': '38,102',
  'label': 'Dynamic_programming,Implementation',
  'name': '반복'},
 {'count': '37,95,62',
  'label': 'Dynamic_programming,Implementation,String',
  'name': '형식'},
 {'count': '35,22,23',
  'label': 'Dynamic_programming,Graph_theory,Greedy',
  'name': '최소화'},
 {'count': '34,22', 'label': 'Dynamic_programming,Graph_theory', 'name': '막대'},
 {'count': '33', 'label': 'Dynamic_programming', 'name': '분할'},
 {'count': '32,30,159,55,43,95',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Graph_traversal,Breadth_first_search,Dijkstras',
  'name': '최단'},
 {'count': '28', 'label': 'Dynamic_programming', 'name': '색깔'},
 {'count': '27,44,66',
  'label': 'Dynamic_programming,Implementation,Graph_theory',
  'name': '영역'},
 {'count': '26', 'label': 'Dynamic_programming', 'name': '메모리'},
 {'count': '22', 'label': 'Dynamic_programming', 'name': '가짓수'},
 {'count': '22', 'label': 'Dynamic_programming', 'name': '3가지'},
 {'count': '22', 'label': 'Dynamic_programming', 'name': '기둥'},
 {'count': '21', 'label': 'Dynamic_programming', 'name': '전봇대'},
 {'count': '20,12', 'label': 'Dynamic_programming,Greedy', 'name': '최선'},
 {'count': '20,107,40',
  'label': 'Dynamic_programming,Graph_theory,Dijkstras',
  'name': '양방향'},
 {'count': '19', 'label': 'Dynamic_programming', 'name': '색상'},
 {'count': '15,53',
  'label': 'Dynamic_programming,Graph_traversal',
  'name': '상하'},
 {'count': '15,44,67,53,37,10',
  'label': 'Dynamic_programming,Implementation,Graph_theory,Graph_traversal,Breadth_first_search,Depth_first_search',
  'name': '상하좌우'},
 {'count': '14', 'label': 'Dynamic_programming', 'name': '북쪽'},
 {'count': '12', 'label': 'Dynamic_programming', 'name': '최소비용'},
 {'count': '12,27',
  'label': 'Dynamic_programming,Implementation',
  'name': '바둑판'},
 {'count': '10', 'label': 'Dynamic_programming', 'name': '2,000,000,000'},
 {'count': '8,6',
  'label': 'Dynamic_programming,Binary_search',
  'name': '10,000,000'},
 {'count': '6', 'label': 'Dynamic_programming', 'name': '동서방향'},
 {'count': '6,31',
  'label': 'Dynamic_programming,Graph_theory',
  'name': '최단거리'},
 {'count': '5', 'label': 'Dynamic_programming', 'name': '이동거리'},
 {'count': '1865,792', 'label': 'Implementation,String', 'name': '출력'},
 {'count': '1319', 'label': 'Implementation', 'name': '때'},
 {'count': '1083', 'label': 'Implementation', 'name': '경우'},
 {'count': '575,325,145',
  'label': 'Implementation,Graph_theory,Breadth_first_search',
  'name': '아래'},
 {'count': '548,882,209,142,112,431,120',
  'label': 'Implementation,Graph_theory,Data_structures,Bruteforcing,Tree,Breadth_first_search,Depth_first_search',
  'name': '이동'},
 {'count': '538', 'label': 'Implementation', 'name': '사람'},
 {'count': '506', 'label': 'Implementation', 'name': '그림'},
 {'count': '485', 'label': 'Implementation', 'name': '테스트'},
 {'count': '481,294,175',
  'label': 'Implementation,Graph_theory,Breadth_first_search',
  'name': '게임'},
 {'count': '456', 'label': 'Implementation', 'name': '케이스'},
 {'count': '379,214,103',
  'label': 'Implementation,Graph_theory,Breadth_first_search',
  'name': '왼쪽'},
 {'count': '344,192,155,100,26',
  'label': 'Implementation,Graph_theory,Graph_traversal,Breadth_first_search,Divide_and_conquer',
  'name': '오른쪽'},
 {'count': '317', 'label': 'Implementation', 'name': '상태'},
 {'count': '277,116', 'label': 'Implementation,String', 'name': '구분'},
 {'count': '261', 'label': 'Implementation', 'name': '결과'},
 {'count': '247', 'label': 'Implementation', 'name': '만약'},
 {'count': '242', 'label': 'Implementation', 'name': '점수'},
 {'count': '217,49', 'label': 'Implementation,Graph_traversal', 'name': '차례'},
 {'count': '185,87', 'label': 'Implementation,Graph_theory', 'name': '보드'},
 {'count': '167,126,93,86',
  'label': 'Implementation,Graph_theory,Greedy,Breadth_first_search',
  'name': '횟수'},
 {'count': '160,43', 'label': 'Implementation,Data_structures', 'name': '세로'},
 {'count': '155,107', 'label': 'Implementation,Graph_theory', 'name': '가로'},
 {'count': '138', 'label': 'Implementation', 'name': '회전'},
 {'count': '133', 'label': 'Implementation', 'name': '기준'},
 {'count': '127', 'label': 'Implementation', 'name': '이후'},
 {'count': '109', 'label': 'Implementation', 'name': '만족'},
 {'count': '108', 'label': 'Implementation', 'name': '시계방향'},
 {'count': '107,33', 'label': 'Implementation,Bruteforcing', 'name': '12'},
 {'count': '104,113', 'label': 'Implementation,Graph_theory', 'name': '높이'},
 {'count': '98', 'label': 'Implementation', 'name': '만큼'},
 {'count': '90,70,59',
  'label': 'Implementation,Graph_theory,Graph_traversal',
  'name': '로봇'},
 {'count': '90', 'label': 'Implementation', 'name': 'm2'},
 {'count': '86,58', 'label': 'Implementation,Graph_theory', 'name': '빈칸'},
 {'count': '86,83', 'label': 'Implementation,Graph_theory', 'name': '구슬'},
 {'count': '82', 'label': 'Implementation', 'name': '가정'},
 {'count': '80', 'label': 'Implementation', 'name': '예제'},
 {'count': '79,263,71,99',
  'label': 'Implementation,Graph_theory,Breadth_first_search,Dijkstras',
  'name': '도착'},
 {'count': '79,255,88',
  'label': 'Implementation,Graph_theory,Breadth_first_search',
  'name': '집'},
 {'count': '79', 'label': 'Implementation', 'name': '제외'},
 {'count': '78', 'label': 'Implementation', 'name': '종료'},
 {'count': '73', 'label': 'Implementation', 'name': '정의'},
 {'count': '71', 'label': 'Implementation', 'name': '조각'},
 {'count': '70', 'label': 'Implementation', 'name': '퍼즐'},
 {'count': '69,177,41,139',
  'label': 'Implementation,Graph_theory,Data_structures,Breadth_first_search',
  'name': '벽'},
 {'count': '67,269', 'label': 'Implementation,Graph_theory', 'name': '길'},
 {'count': '66,55', 'label': 'Implementation,Graph_theory', 'name': '타일'},
 {'count': '65,510,63',
  'label': 'Implementation,Graph_theory,Depth_first_search',
  'name': '경로'},
 {'count': '64', 'label': 'Implementation', 'name': '플레이어'},
 {'count': '63,95,58',
  'label': 'Implementation,Graph_theory,Graph_traversal',
  'name': '다리'},
 {'count': '60,121,49,23,35,27',
  'label': 'Implementation,Graph_theory,Greedy,Bruteforcing,Tree,Depth_first_search',
  'name': '10,000'},
 {'count': '60', 'label': 'Implementation', 'name': '주사위'},
 {'count': '60', 'label': 'Implementation', 'name': '최종'},
 {'count': '60', 'label': 'Implementation', 'name': '스티커'},
 {'count': '59', 'label': 'Implementation', 'name': '좌우'},
 {'count': '56', 'label': 'Implementation', 'name': '승리'},
 {'count': '53,63', 'label': 'Implementation,Data_structures', 'name': '범위'},
 {'count': '53', 'label': 'Implementation', 'name': '상황'},
 {'count': '52,35', 'label': 'Implementation,Data_structures', 'name': '게임판'},
 {'count': '51,110,64',
  'label': 'Implementation,Graph_theory,Graph_traversal',
  'name': '도달'},
 {'count': '49', 'label': 'Implementation', 'name': '발견'},
 {'count': '45,18', 'label': 'Implementation,Graph_theory', 'name': '경계'},
 {'count': '44', 'label': 'Implementation', 'name': '가운데'},
 {'count': '42', 'label': 'Implementation', 'name': '보장'},
 {'count': '42,111,58,26',
  'label': 'Implementation,Graph_theory,Graph_traversal,Depth_first_search',
  'name': '지역'},
 {'count': '41', 'label': 'Implementation', 'name': '강'},
 {'count': '41', 'label': 'Implementation', 'name': '모눈'},
 {'count': '41', 'label': 'Implementation', 'name': '몬스터'},
 {'count': '40,11', 'label': 'Implementation,Graph_theory', 'name': '모눈종이'},
 {'count': '40', 'label': 'Implementation', 'name': '큐브'},
 {'count': '39', 'label': 'Implementation', 'name': '해결'},
 {'count': '39,37,17',
  'label': 'Implementation,Graph_theory,Breadth_first_search',
  'name': '대각선'},
 {'count': '38', 'label': 'Implementation', 'name': '속도'},
 {'count': '37,630,188,81,111,225',
  'label': 'Implementation,Graph_theory,Data_structures,Greedy,Graph_traversal,Tree',
  'name': '도로'},
 {'count': '37', 'label': 'Implementation', 'name': '알고리즘'},
 {'count': '37,33', 'label': 'Implementation,Tree', 'name': '레벨'},
 {'count': '36', 'label': 'Implementation', 'name': '기차'},
 {'count': '35,122,78,73,41',
  'label': 'Implementation,Graph_theory,Graph_traversal,Breadth_first_search,Dijkstras',
  'name': '탈출'},
 {'count': '35', 'label': 'Implementation', 'name': '성공'},
 {'count': '35', 'label': 'Implementation', 'name': '109'},
 {'count': '34,18', 'label': 'Implementation,Bruteforcing', 'name': '18'},
 {'count': '33,405,156,99,122,17,64',
  'label': 'Implementation,Graph_theory,Data_structures,Graph_traversal,Tree,Breadth_first_search,Depth_first_search',
  'name': '그래프'},
 {'count': '32,105', 'label': 'Implementation,Graph_theory', 'name': '여행'},
 {'count': '31', 'label': 'Implementation', 'name': '포인트'},
 {'count': '30,53', 'label': 'Implementation,Graph_theory', 'name': '통과'},
 {'count': '30', 'label': 'Implementation', 'name': '달팽이'},
 {'count': '30', 'label': 'Implementation', 'name': '유저'},
 {'count': '29', 'label': 'Implementation', 'name': '톱니바퀴'},
 {'count': '28', 'label': 'Implementation', 'name': '감소'},
 {'count': '28', 'label': 'Implementation', 'name': '우선'},
 {'count': '27,73,66,53',
  'label': 'Implementation,Graph_theory,Graph_traversal,Breadth_first_search',
  'name': '장애물'},
 {'count': '27,67,51,51,135,37',
  'label': 'Implementation,Graph_theory,Data_structures,Graph_traversal,Tree,Depth_first_search',
  'name': '루트'},
 {'count': '27,29', 'label': 'Implementation,Graph_theory', 'name': '그리드'},
 {'count': '27,167,111,101',
  'label': 'Implementation,Graph_theory,Graph_traversal,Breadth_first_search',
  'name': '미로'},
 {'count': '27,24,21',
  'label': 'Implementation,Graph_theory,Graph_traversal',
  'name': '산책로'},
 {'count': '25', 'label': 'Implementation', 'name': '공격력'},
 {'count': '25', 'label': 'Implementation', 'name': '곤돌라'},
 {'count': '22', 'label': 'Implementation', 'name': '28'},
 {'count': '22', 'label': 'Implementation', 'name': '22'},
 {'count': '22', 'label': 'Implementation', 'name': '106'},
 {'count': '22', 'label': 'Implementation', 'name': '고려'},
 {'count': '21', 'label': 'Implementation', 'name': '64'},
 {'count': '21', 'label': 'Implementation', 'name': '서쪽'},
 {'count': '21', 'label': 'Implementation', 'name': '35'},
 {'count': '20', 'label': 'Implementation', 'name': '300'},
 {'count': '20', 'label': 'Implementation', 'name': '105'},
 {'count': '19', 'label': 'Implementation', 'name': '80'},
 {'count': '19', 'label': 'Implementation', 'name': '99'},
 {'count': '19', 'label': 'Implementation', 'name': '36'},
 {'count': '19', 'label': 'Implementation', 'name': '필드'},
 {'count': '19', 'label': 'Implementation', 'name': '총합'},
 {'count': '18', 'label': 'Implementation', 'name': '전진'},
 {'count': '18', 'label': 'Implementation', 'name': '빌딩'},
 {'count': '18', 'label': 'Implementation', 'name': '놀이판'},
 {'count': '17', 'label': 'Implementation', 'name': '커브'},
 {'count': '17', 'label': 'Implementation', 'name': '상자'},
 {'count': '16', 'label': 'Implementation', 'name': '룰'},
 {'count': '16', 'label': 'Implementation', 'name': '사다리'},
 {'count': '16,26', 'label': 'Implementation,Data_structures', 'name': '구현'},
 {'count': '16', 'label': 'Implementation', 'name': '스도쿠'},
 {'count': '15', 'label': 'Implementation', 'name': '윤년'},
 {'count': '11', 'label': 'Implementation', 'name': '이내'},
 {'count': '11', 'label': 'Implementation', 'name': '마방진'},
 {'count': '10', 'label': 'Implementation', 'name': '확산'},
 {'count': '941', 'label': 'Graph_theory', 'name': '다음'},
 {'count': '737,286,101,128',
  'label': 'Graph_theory,Data_structures,Breadth_first_search,Dijkstras',
  'name': '연결'},
 {'count': '699,170', 'label': 'Graph_theory,Data_structures', 'name': '칸'},
 {'count': '659,386,568,61,188',
  'label': 'Graph_theory,Data_structures,Tree,Breadth_first_search,Depth_first_search',
  'name': '정점'},
 {'count': '641,257,163,278,56,50',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Tree,Breadth_first_search,Depth_first_search',
  'name': '도시'},
 {'count': '534,214,163,276,31,107,73',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Tree,Breadth_first_search,Depth_first_search,Dijkstras',
  'name': '간선'},
 {'count': '305,209,213,599,144',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Tree,Depth_first_search',
  'name': '트리'},
 {'count': '296,128,88,137,97,120',
  'label': 'Graph_theory,Data_structures,Greedy,Graph_traversal,Breadth_first_search,Dijkstras',
  'name': '거리'},
 {'count': '291,62,47,44',
  'label': 'Graph_theory,Breadth_first_search,Depth_first_search,Dijkstras',
  'name': '모든'},
 {'count': '286,94,44',
  'label': 'Graph_theory,Breadth_first_search,Depth_first_search',
  'name': '시작'},
 {'count': '248', 'label': 'Graph_theory', 'name': '각각'},
 {'count': '244,90,32',
  'label': 'Graph_theory,Greedy,Priority_queue',
  'name': '비용'},
 {'count': '242', 'label': 'Graph_theory', 'name': '방'},
 {'count': '224,260,132,46',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Depth_first_search',
  'name': '점'},
 {'count': '215', 'label': 'Graph_theory', 'name': '곳'},
 {'count': '214,95,69,73',
  'label': 'Graph_theory,Graph_traversal,Breadth_first_search,Dijkstras',
  'name': '지점'},
 {'count': '212,138,107,36',
  'label': 'Graph_theory,Graph_traversal,Breadth_first_search,Depth_first_search',
  'name': '지도'},
 {'count': '209,71,36,25',
  'label': 'Graph_theory,Breadth_first_search,Depth_first_search,Divide_and_conquer',
  'name': '가지'},
 {'count': '182', 'label': 'Graph_theory', 'name': '자신'},
 {'count': '179,92', 'label': 'Graph_theory,Number_theory', 'name': '숫자'},
 {'count': '175,41,41,13,68',
  'label': 'Graph_theory,Data_structures,Breadth_first_search,Depth_first_search,Dijkstras',
  'name': '출발'},
 {'count': '170,68,136,265,118',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Tree,Depth_first_search',
  'name': '노드'},
 {'count': '158', 'label': 'Graph_theory', 'name': '현재'},
 {'count': '155,60', 'label': 'Graph_theory,Data_structures', 'name': '마을'},
 {'count': '153,76,77,61',
  'label': 'Graph_theory,Data_structures,Graph_traversal,Tree',
  'name': '방문'},
 {'count': '149,91,61,94,69,25,23',
  'label': 'Graph_theory,Greedy,Graph_traversal,Tree,Binary_search,Depth_first_search,Priority_queue',
  'name': '100,000'},
 {'count': '146', 'label': 'Graph_theory', 'name': '나라'},
 {'count': '137', 'label': 'Graph_theory', 'name': '선'},
 {'count': '128,41', 'label': 'Graph_theory,Data_structures', 'name': '건물'},
 {'count': '120', 'label': 'Graph_theory', 'name': '교차로'},
 {'count': '89,106', 'label': 'Graph_theory,Data_structures', 'name': '나무'},
 {'count': '84,52', 'label': 'Graph_theory,Bruteforcing', 'name': '50'},
 {'count': '82,30,15',
  'label': 'Graph_theory,Greedy,Bruteforcing',
  'name': '1000'},
 {'count': '79', 'label': 'Graph_theory', 'name': '목표'},
 {'count': '76', 'label': 'Graph_theory', 'name': '동시'},
 {'count': '73,58', 'label': 'Graph_theory,Graph_traversal', 'name': '블록'},
 {'count': '72,82', 'label': 'Graph_theory,Data_structures', 'name': '선분'},
 {'count': '70,23', 'label': 'Graph_theory,Graph_traversal', 'name': '동굴'},
 {'count': '69', 'label': 'Graph_theory', 'name': '장소'},
 {'count': '61,20,13',
  'label': 'Graph_theory,Data_structures,Breadth_first_search',
  'name': '네트워크'},
 {'count': '59,21',
  'label': 'Graph_theory,Breadth_first_search',
  'name': '시작점'},
 {'count': '58', 'label': 'Graph_theory', 'name': '바이러스'},
 {'count': '58,29',
  'label': 'Graph_theory,Breadth_first_search',
  'name': '목적지'},
 {'count': '57', 'label': 'Graph_theory', 'name': '사이클'},
 {'count': '56,45', 'label': 'Graph_theory,Data_structures', 'name': '국가'},
 {'count': '48', 'label': 'Graph_theory', 'name': '중복'},
 {'count': '48', 'label': 'Graph_theory', 'name': '개구리'},
 {'count': '45', 'label': 'Graph_theory', 'name': '화살표'},
 {'count': '45', 'label': 'Graph_theory', 'name': '통로'},
 {'count': '45,22,21',
  'label': 'Graph_theory,Breadth_first_search,Dijkstras',
  'name': '출발지'},
 {'count': '43', 'label': 'Graph_theory', 'name': '입구'},
 {'count': '43', 'label': 'Graph_theory', 'name': '복도'},
 {'count': '42', 'label': 'Graph_theory', 'name': '링크'},
 {'count': '38,19,13',
  'label': 'Graph_theory,Data_structures,Binary_search',
  'name': '탐색'},
 {'count': '36,12,9',
  'label': 'Graph_theory,Data_structures,Tree',
  'name': '스패닝'},
 {'count': '35', 'label': 'Graph_theory', 'name': '통행'},
 {'count': '34', 'label': 'Graph_theory', 'name': '뿌리'},
 {'count': '33', 'label': 'Graph_theory', 'name': '골목'},
 {'count': '32', 'label': 'Graph_theory', 'name': '200'},
 {'count': '32,24,9',
  'label': 'Graph_theory,Graph_traversal,Binary_search',
  'name': '검색'},
 {'count': '24,14', 'label': 'Graph_theory,Data_structures', 'name': '무방향'},
 {'count': '24', 'label': 'Graph_theory', 'name': '자판'},
 {'count': '24', 'label': 'Graph_theory', 'name': '왕국'},
 {'count': '24', 'label': 'Graph_theory', 'name': '자동차'},
 {'count': '24', 'label': 'Graph_theory', 'name': '교차점'},
 {'count': '23', 'label': 'Graph_theory', 'name': '도로망'},
 {'count': '22', 'label': 'Graph_theory', 'name': '방향성'},
 {'count': '22', 'label': 'Graph_theory', 'name': '수로'},
 {'count': '22', 'label': 'Graph_theory', 'name': '공항'},
 {'count': '22', 'label': 'Graph_theory', 'name': '연못'},
 {'count': '21', 'label': 'Graph_theory', 'name': '10000'},
 {'count': '21', 'label': 'Graph_theory', 'name': '오솔길'},
 {'count': '20', 'label': 'Graph_theory', 'name': '호수'},
 {'count': '20', 'label': 'Graph_theory', 'name': '일방통행'},
 {'count': '20', 'label': 'Graph_theory', 'name': '철도'},
 {'count': '20', 'label': 'Graph_theory', 'name': '미궁'},
 {'count': '19', 'label': 'Graph_theory', 'name': '너비'},
 {'count': '19', 'label': 'Graph_theory', 'name': '도착지'},
 {'count': '17', 'label': 'Graph_theory', 'name': '통행료'},
 {'count': '16', 'label': 'Graph_theory', 'name': '가로등'},
 {'count': '16', 'label': 'Graph_theory', 'name': '골목길'},
 {'count': '15', 'label': 'Graph_theory', 'name': '코스'},
 {'count': '12', 'label': 'Graph_theory', 'name': '바둑'},
 {'count': '12', 'label': 'Graph_theory', 'name': '탐험'},
 {'count': '2648', 'label': 'Data_structures', 'name': '줄'},
 {'count': '344,874', 'label': 'Data_structures,String', 'name': '문자열'},
 {'count': '157', 'label': 'Data_structures', 'name': '양'},
 {'count': '138', 'label': 'Data_structures', 'name': '쌍'},
 {'count': '136,20', 'label': 'Data_structures,Priority_queue', 'name': '원소'},
 {'count': '115', 'label': 'Data_structures', 'name': '데이터'},
 {'count': '109,60,23',
  'label': 'Data_structures,Greedy,Stack',
  'name': '마지막'},
 {'count': '101', 'label': 'Data_structures', 'name': '형태'},
 {'count': '95', 'label': 'Data_structures', 'name': '구성'},
 {'count': '88,57',
  'label': 'Data_structures,Depth_first_search',
  'name': '섬'},
 {'count': '73', 'label': 'Data_structures', 'name': '배치'},
 {'count': '50', 'label': 'Data_structures', 'name': '평면'},
 {'count': '44', 'label': 'Data_structures', 'name': '수도'},
 {'count': '42', 'label': 'Data_structures', 'name': '손님'},
 {'count': '37,36', 'label': 'Data_structures,Stack', 'name': '스택'},
 {'count': '36', 'label': 'Data_structures', 'name': '교차'},
 {'count': '34,25', 'label': 'Data_structures,Binary_search', 'name': '오름차'},
 {'count': '34', 'label': 'Data_structures', 'name': '공간'},
 {'count': '30', 'label': 'Data_structures', 'name': '큐'},
 {'count': '29', 'label': 'Data_structures', 'name': '인덱스'},
 {'count': '23', 'label': 'Data_structures', 'name': '자료'},
 {'count': '21,21', 'label': 'Data_structures,Stack', 'name': '포인터'},
 {'count': '20', 'label': 'Data_structures', 'name': '리스트'},
 {'count': '15', 'label': 'Data_structures', 'name': '비트'},
 {'count': '12', 'label': 'Data_structures', 'name': '두더지'},
 {'count': '12', 'label': 'Data_structures', 'name': '삼각형'},
 {'count': '11', 'label': 'Data_structures', 'name': '자료구조'},
 {'count': '11', 'label': 'Data_structures', 'name': '주소'},
 {'count': '147', 'label': 'Greedy', 'name': '이상'},
 {'count': '112', 'label': 'Greedy', 'name': '이하'},
 {'count': '80', 'label': 'Greedy', 'name': '정보'},
 {'count': '76,115', 'label': 'Greedy,Bruteforcing', 'name': '100'},
 {'count': '41', 'label': 'Greedy', 'name': '정답'},
 {'count': '19', 'label': 'Greedy', 'name': '제일'},
 {'count': '18', 'label': 'Greedy', 'name': '최고'},
 {'count': '14', 'label': 'Greedy', 'name': '효율적'},
 {'count': '14', 'label': 'Greedy', 'name': '최종적'},
 {'count': '500', 'label': 'String', 'name': '단어'},
 {'count': '383', 'label': 'String', 'name': '알파벳'},
 {'count': '336', 'label': 'String', 'name': '문자'},
 {'count': '316', 'label': 'String', 'name': '작성'},
 {'count': '266', 'label': 'String', 'name': '개수'},
 {'count': '262', 'label': 'String', 'name': '소문자'},
 {'count': '231', 'label': 'String', 'name': '개의'},
 {'count': '227', 'label': 'String', 'name': '글자'},
 {'count': '221', 'label': 'String', 'name': '이름'},
 {'count': '201', 'label': 'String', 'name': '공백'},
 {'count': '148', 'label': 'String', 'name': '문장'},
 {'count': '139', 'label': 'String', 'name': '대문자'},
 {'count': '132', 'label': 'String', 'name': '사전'},
 {'count': '89', 'label': 'String', 'name': '연산자'},
 {'count': '78', 'label': 'String', 'name': '영어'},
 {'count': '46', 'label': 'String', 'name': '암호'},
 {'count': '45', 'label': 'String', 'name': '암호화'},
 {'count': '44', 'label': 'String', 'name': '팰린드롬'},
 {'count': '39', 'label': 'String', 'name': '언어'},
 {'count': '38', 'label': 'String', 'name': '접미사'},
 {'count': '31', 'label': 'String', 'name': '평문'},
 {'count': '25', 'label': 'String', 'name': '띄어쓰기'},
 {'count': '25', 'label': 'String', 'name': '텍스트'},
 {'count': '22', 'label': 'String', 'name': '비밀번호'},
 {'count': '22', 'label': 'String', 'name': '접두사'},
 {'count': '16', 'label': 'String', 'name': '채팅'},
 {'count': '15', 'label': 'String', 'name': '워드'},
 {'count': '14', 'label': 'String', 'name': '심볼'},
 {'count': '120,33', 'label': 'Graph_traversal,Dijkstras', 'name': '방법'},
 {'count': '78', 'label': 'Graph_traversal', 'name': '처음'},
 {'count': '58', 'label': 'Graph_traversal', 'name': '단위'},
 {'count': '541', 'label': 'Bruteforcing', 'name': '2'},
 {'count': '386', 'label': 'Bruteforcing', 'name': '3'},
 {'count': '103', 'label': 'Bruteforcing', 'name': '7'},
 {'count': '86', 'label': 'Bruteforcing', 'name': '8'},
 {'count': '44', 'label': 'Bruteforcing', 'name': '불가능'},
 {'count': '43', 'label': 'Bruteforcing', 'name': '20'},
 {'count': '35', 'label': 'Bruteforcing', 'name': '15'},
 {'count': '33', 'label': 'Bruteforcing', 'name': '13'},
 {'count': '32', 'label': 'Bruteforcing', 'name': '1,000'},
 {'count': '23', 'label': 'Bruteforcing', 'name': '30'},
 {'count': '21', 'label': 'Bruteforcing', 'name': '11'},
 {'count': '18', 'label': 'Bruteforcing', 'name': '14'},
 {'count': '17', 'label': 'Bruteforcing', 'name': '500'},
 {'count': '17', 'label': 'Bruteforcing', 'name': '23'},
 {'count': '16', 'label': 'Bruteforcing', 'name': '21'},
 {'count': '15', 'label': 'Bruteforcing', 'name': '선형'},
 {'count': '14', 'label': 'Bruteforcing', 'name': '일정'},
 {'count': '14', 'label': 'Bruteforcing', 'name': '32'},
 {'count': '14', 'label': 'Bruteforcing', 'name': '40'},
 {'count': '33', 'label': 'Tree', 'name': '직속'},
 {'count': '21,13,7',
  'label': 'Tree,Binary_search,Priority_queue',
  'name': '200,000'},
 {'count': '20,7', 'label': 'Tree,Binary_search', 'name': '300,000'},
 {'count': '10', 'label': 'Tree', 'name': '50,000'},
 {'count': '9,15', 'label': 'Tree,Binary_search', 'name': '500,000'},
 {'count': '7', 'label': 'Tree', 'name': '200000'},
 {'count': '15', 'label': 'Binary_search', 'name': '-1,000,000,000'},
 {'count': '9', 'label': 'Binary_search', 'name': '100000'},
 {'count': '7', 'label': 'Binary_search', 'name': '내림차'},
 {'count': '6', 'label': 'Binary_search', 'name': '100,000,000'},
 {'count': '4', 'label': 'Binary_search', 'name': '-10,000,000'},
 {'count': '4', 'label': 'Binary_search', 'name': '1000000'},
 {'count': '258,116,72',
  'label': 'Number_theory,Dijkstras,Priority_queue',
  'name': '첫째'},
 {'count': '62,51,25',
  'label': 'Number_theory,Divide_and_conquer,Stack',
  'name': '둘째'},
 {'count': '15', 'label': 'Number_theory', 'name': '분자'},
 {'count': '13', 'label': 'Number_theory', 'name': '수학자'},
 {'count': '11', 'label': 'Number_theory', 'name': '서로소'},
 {'count': '158,96',
  'label': 'Breadth_first_search,Depth_first_search',
  'name': '프로그램'},
 {'count': '85', 'label': 'Breadth_first_search', 'name': '행'},
 {'count': '30', 'label': 'Dijkstras', 'name': '총'},
 {'count': '32', 'label': 'Divide_and_conquer', 'name': '수평선'},
 {'count': '6', 'label': 'Divide_and_conquer', 'name': '절반'},
 {'count': '46', 'label': 'Stack', 'name': '위'},
 {'count': '27', 'label': 'Stack', 'name': '앞'},
 {'count': '20', 'label': 'Priority_queue', 'name': '추가'},
 {'count': '20', 'label': 'Priority_queue', 'name': '순위'},
 {'count': '8', 'label': 'Priority_queue', 'name': '우선순위'}]

label_keyword_ratio = {'Mathematics': 0.163, 'Dynamic_programming': 0.121, 'Implementation': 0.126, 'Graph_theory': 0.099, 'Data_structures': 0.089, 'Greedy': 0.049, 'String': 0.054, 'Graph_traversal': 0.053, 'Bruteforcing': 0.044, 'Tree': 0.034, 'Binary_search': 0.033, 'Number_theory': 0.035, 'Breadth_first_search': 0.031, 'Depth_first_search': 0.018, 'Dijkstras': 0.017, 'Divide_and_conquer': 0.014, 'Stack': 0.01, 'Priority_queue': 0.01}
label_noun_count = {'Mathematics': 102316, 'Dynamic_programming': 96736, 'Implementation': 108441, 'Graph_theory': 97609, 'Data_structures': 79071, 'Greedy': 35973, 'String': 33824, 'Graph_traversal': 46796, 'Bruteforcing': 32508, 'Tree': 29268, 'Binary_search': 23773, 'Number_theory': 16448, 'Breadth_first_search': 26511, 'Depth_first_search': 14156, 'Dijkstras': 16200, 'Divide_and_conquer': 9488, 'Stack': 6390, 'Priority_queue': 6317}
label_problem_count = {'Mathematics': 1377, 'Dynamic_programming': 1022, 'Implementation': 1058, 'Graph_theory': 835, 'Data_structures': 753, 'Greedy': 412, 'String': 452, 'Graph_traversal': 446, 'Bruteforcing': 373, 'Tree': 284, 'Binary_search': 275, 'Number_theory': 293, 'Breadth_first_search': 260, 'Depth_first_search': 154, 'Dijkstras': 143, 'Divide_and_conquer': 120, 'Stack': 83, 'Priority_queue': 86}

'''
export keywords to csv file
'''

import pandas as pd

if __name__ == "__main__" :
     pd.DataFrame(keyword_list).to_csv('keyword.csv')